main page design layout
e-garbuzov-wise/instagram-like-trainee pull request #2
Opened 2024-03-21 10:40 UTC by e-garbuzov-wise

2024-03-21 11:05 UTC, EugeneKirilovIOSDev requested changes

2024-03-21 11:05 UTC, EugeneKirilovIOSDev commented on Instagram-like-trainee/MainPage/View/CollectionViewCell/PostCell/PostHeaderCell.swift
>  class PostHeaderCell: UICollectionViewCell {
Same

2024-03-21 11:05 UTC, EugeneKirilovIOSDev commented on Instagram-like-trainee/MainPage/View/MainPageViewController.swift
>          let headerSection = NSCollectionLayoutSection(group: headerGroup)
Please use methods of UICollectionView data source and delegate, just rewrite it, not good solution for now

2024-03-21 11:05 UTC, EugeneKirilovIOSDev commented on Instagram-like-trainee/MainPage/View/MainPageViewController.swift
Here also, find some methods of delegate and data source

2024-03-21 11:05 UTC, EugeneKirilovIOSDev commented on Instagram-like-trainee/MainPage/View/MainPageViewController.swift
>      func numberOfSections(in collectionView: UICollectionView) -> Int {
Don't forget to use MARK before extensions and for some code blocks separation

2024-03-21 11:05 UTC, EugeneKirilovIOSDev commented on Instagram-like-trainee/MainPage/View/MainPageViewController.swift
> +                image.contentMode = .scaleAspectFill
Too much if operators, try to find better solution, use generative AI for code refactoring

2024-03-22 07:25 UTC, e-garbuzov-wise commented on Instagram-like-trainee/Assets.xcassets/insta-logo.imageset/Instagram_logo.svg-2.png
fix

2024-03-22 07:25 UTC, e-garbuzov-wise commented on Instagram-like-trainee/Assets.xcassets/elon-musk.imageset/gettyimages-1229892983-square.jpg
fix

2024-03-22 09:08 UTC, e-garbuzov-wise commented on Instagram-like-trainee/MainPage/View/CollectionViewCell/HomeFeedHeaderCell.swift
> +    let logoIamgeView = UIImageView()
fix

2024-03-22 09:10 UTC, e-garbuzov-wise commented on Instagram-like-trainee/MainPage/View/CollectionViewCell/HomeFeedHeaderCell.swift
>  class HomeFeedHeaderCell: UICollectionViewCell {
fix

2024-03-22 09:11 UTC, e-garbuzov-wise commented on Instagram-like-trainee/MainPage/View/CollectionViewCell/PostCell/PostActionCell.swift
>  class PostActionCell: UICollectionViewCell {
fix

2024-03-25 11:05 UTC, merged